Version: 1.5 # minimal SMASH version to use with this config file

Logging:
    default: INFO

General:
    Modus:          Collider
    Time_Step_Mode: Fixed
    Delta_Time:     0.01
    End_Time:       100.0
    Randomseed:     randomrandom
    Nevents:        numberofevents
    Gaussian_Sigma: 1.0
    Gauss_Cutoff_In_Sigma: 4.0
    Use_Grid: True

Output:
    Output_Interval: 10.0
    Density_Type: "baryon"
    Particles:
        Format:     ["Root"]
        Extended:   True
        Only_Final: True
#    Collisions:
#        Format:     ["Root"]
#        Extended:   True
#        Print_Start_End: True

Modi:
    Collider:
        Projectile:
            Particles: {2212: 79, 2112: 118} #Gold197
        Target:
            Particles: {2212: 79, 2112: 118} #Gold197
        Impact:
            Sample: "quadratic"
            Range:  [0.0, 18.0]    #[0.0, 14.0] 

        Sqrtsnn: energyincms
        Fermi_Motion: "on"	#frozen / on ? then delta_time 0.01 for Snn=5

Potentials:
    Skyrme:
        Skyrme_A: -209.2
        Skyrme_B: 156.4
        Skyrme_Tau: 1.35
    Symmetry:
        S_Pot: 18.0
#default
#           a [MeV]   b [MeV]     t    S_pot [MeV]
#
#default    -209.2    156.4     1.35    18
#
#soft       -356.0    303.0     1.17    18
#
#hard       -124.0    71.0      2.0     18
